{{- if and .Values.rbac.create (eq .Values.agent.rbac.scope "namespace") }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "mechanic.agentNSSAName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mechanic.labels" . | nindent 4 }}
{{- end }}
