apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mendabot.fullname" . }}-crd-upgrader
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mendabot.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-upgrade,pre-install
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
data:
  remediationjob.yaml: |
    {{- .Files.Get "crds/remediationjob.yaml" | nindent 4 }}
