{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "mendabot.fullname" . }}-agent
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mendabot.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "mendabot.fullname" . }}-agent
subjects:
- kind: ServiceAccount
  name: {{ include "mendabot.agentSAName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
