{{- if .Values.metrics.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mendabot.fullname" . }}-metrics
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mendabot.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "mendabot.selectorLabels" . | nindent 4 }}
  ports:
  - name: metrics
    port: 8080
    targetPort: 8080
    protocol: TCP
{{- end }}
